/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ch.genevajug

import ch.genevajug.eventbrite.EventBriteService
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication

@SpringBootApplication
class DemoApplication

fun main(args: Array<String>) {
    val ctx = runApplication<DemoApplication>(*args)

    val bean = ctx.getBean(EventBriteService::class.java)
    val category = bean.categoriesList()
    println("Categories are : ")
    println(category)
    for (category in category.categories) {
        println(" - ${category}" )
    }


}
