/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ch.genevajug

import junit.framework.Assert.assertNotNull
import org.junit.Test

class AppTest {
    @Test
    fun testAppHasAGreeting() {
        assertNotNull("", "app should have a greeting")
    }
}
